f1 = open('rumenjiFinal.txt', 'r')
f2 = open('Sudoku_level1.json','w')
f2.write("var sudokuGame = [\n")
for num in range(1,1001):
    f2.write("{\n")
    f2.write("\tid: \'"+str(num)+"\',\n")
    f2.write("\tlevel: \'1\',\n")
    f2.write("\tdata: \'")
    for j in range(1,11):
        f2.write("\t\t\t\t\t")
        temp = f1.readline()
        f2.write(temp)
    f2.write("\'\n},\n")
f1.close()
f1 = open('chujiFinal', 'r')
for num in range(1001,2001):
    f2.write("{\n")
    f2.write("\tid: \'"+str(num)+"\',\n")
    f2.write("\tlevel: \'2\',\n")
    f2.write("\tdata: \'")
    for j in range(1,11):
        f2.write("\t\t\t\t\t")
        temp = f1.readline()
        f2.write(temp)
    f2.write("\'\n},\n")
f1.close()
f1 = open('zhongjiFinal', 'r')
for num in range(2001,3001):
    f2.write("{\n")
    f2.write("\tid: \'"+str(num)+"\',\n")
    f2.write("\tlevel: \'3\',\n")
    f2.write("\tdata: \'")
    for j in range(1,11):
        f2.write("\t\t\t\t\t")
        temp = f1.readline()
        f2.write(temp)
    f2.write("\'\n},\n")
f1.close()
f1 = open('gaojiFinal', 'r')
for num in range(3001,4001):
    f2.write("{\n")
    f2.write("\tid: \'"+str(num)+"\',\n")
    f2.write("\tlevel: \'4\',\n")
    f2.write("\tdata: \'")
    for j in range(1,11):
        f2.write("\t\t\t\t\t")
        temp = f1.readline()
        f2.write(temp)
    f2.write("\'\n},\n")
f1.close()
f1 = open('guhuijiFinal', 'r')
for num in range(4001,5001):
    f2.write("{\n")
    f2.write("\tid: \'"+str(num)+"\',\n")
    f2.write("\tlevel: \'5\',\n")
    f2.write("\tdata: \'\n")
    for j in range(1,11):
        f2.write("\t\t\t\t\t")
        temp = f1.readline()
        f2.write(temp)
    f2.write("\t\t\t\t\t\'\n},\n")
f2.write("]")
f1.close()
f2.close()